### ISSUE TITLE
.net 5 support

### ISSUE THREAD

**Issue by ismailmayat** [valeraf23/VF.OpenTelemetry#1]
I am looking to use VF.OpenTelemetry in .net5 console kafka producer however I get error:

` [CS0103] The name 'VFSdk' does not exist in the current context`

Is .net 5 supported?

Many thanks.

**Comment by valeraf23** [comment]
need to use Sdk

https://github.com/valeraf23/VF.OpenTelemetry/blob/main/vf-instrumentation-sdk/src/VF.Logging.OpenTelemetry/Sdk.cs

**Comment by valeraf23** [comment]
need to update package in eaxamples
